export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_ERROR = 'FETCH_RESTAURANTS_ERROR';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';

export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

//might delete this one later
export const FETCH_RECORDS_SUCCESS = 'FETCH_RECORDS_SUCCESS';


export const SET_CURRENT_WEEK_START = 'SET_CURRENT_WEEK_START';
export const SET_CURRENT_WEEK_END = 'SET_CURRENT_WEEK_END';
