export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_ERROR = 'FETCH_RESTAURANTS_ERROR';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';


export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CLEAR_FETCHED_ITEMS = 'CLEAR_FETCHED_ITEMS';
export const UPDATE_RECORD = 'UPDATE_RECORD';

export const FETCH_RECORDS_SUCCESS = 'FETCH_RECORDS_SUCCESS';
export const FETCH_RECORDS_ERROR = 'FETCH_RECORDS_ERROR';


export const SET_CURRENT_WORK_DAY = 'SET_CURRENT_WORK_DAY';
export const SET_PREVIOUS_WORK_DAY = 'SET_PREVIOUS_WORK_DAY';


export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';